Candidate.create!(first_name: 'Robert', last_name: 'Stokes')
Candidate.create!(first_name: 'Phillip', last_name: 'Westry')
Candidate.create!(first_name: 'Dave', last_name: 'Heikler')
Candidate.create!(first_name: 'Gary', last_name: 'Crum')
Candidate.create!(first_name: 'Kelly', last_name: 'Cross')
